#!/bin/bash

repo_name=$1
test -z $repo_name && echo $'Error: repo name required'\
                           $'\nusage: github-init [repo_name]' 1>&2 && exit 1
                           # 1>&2 redirects echo from stdout to stderr

url="https://api.github.com/user/repos"

echo -n "Username for \"$url\": "
read username

curl -u "$username" $url -d "{\"name\":\"$repo_name\"}"

git init
git remote add origin "https://github.com/$username/$repo_name.git"
